kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    # Extra mounts for eBPF support
    extraMounts:
      - hostPath: /sys/fs/bpf
        containerPath: /sys/fs/bpf
        propagation: Bidirectional
      - hostPath: /sys/kernel/debug
        containerPath: /sys/kernel/debug
        propagation: None
  - role: worker
    extraMounts:
      - hostPath: /sys/fs/bpf
        containerPath: /sys/fs/bpf
        propagation: Bidirectional
      - hostPath: /sys/kernel/debug
        containerPath: /sys/kernel/debug
        propagation: None
  - role: worker
    extraMounts:
      - hostPath: /sys/fs/bpf
        containerPath: /sys/fs/bpf
        propagation: Bidirectional
      - hostPath: /sys/kernel/debug
        containerPath: /sys/kernel/debug
        propagation: None
  - role: worker
    extraMounts:
      - hostPath: /sys/fs/bpf
        containerPath: /sys/fs/bpf
        propagation: Bidirectional
      - hostPath: /sys/kernel/debug
        containerPath: /sys/kernel/debug
        propagation: None
